version: 0.2
phases:
  pre_build:
    commands:
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.17/2023-11-14/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - cp ./kubectl /bin/kubectl && export PATH=/bin:$PATH
      - echo 'export PATH=/bin:$PATH' >> ~/.bashrc
      - aws eks --region ap-northeast-2 update-kubeconfig --name eks-cluster-2
      - kubectl get pod -n kube-system
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/
  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - AWS_ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - DATE='date'
      - echo Build completed on $DATE
      - sed -i.bak 's#AWS_ECR_URI#'"$AWS_ECR_URI"'#' ./prod/deployment.yaml
      - sed -i.bak 's#DATE_STRING#'"$DATE"'#' ./prod/deployment.yaml
      - kubectl apply -f ./prod/deployment.yaml
      - kubectl apply -f ./prod/service.yaml
