apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-nginx-app
  template:
    metadata:
      labels:
        app: demo-nginx-app
    spec:
      containers:
      - image: AWS_ECR_URI
        name: demo-nginx-app
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env: 
        - name: DATE
          value: 'DATE_STRING'

