apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-nginx-app
  template:
    metadata:
      labels:
        app: demo-cicd-nginx-app
    spec:
      containers:
      - image: 870226762666.dkr.ecr.ap-northeast-2.amazonaws.com/web_image:0.1
        name: demo-nginx-app
        ports:
        - containerPort: 80
