apiVersion: v1
kind: Service
metadata:
  name: demo-nginx-app
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"    
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0f6aad2bd7b5626d0
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: demo-nginx-app
